### ISSUE TITLE
Onslaught not supported

### ISSUE THREAD

**Issue by Calypto** [EliotVU/UT2004-MutEmoticons#2]
Hello again, if I attempt to use MutEmoticons with onslaught, the onslaught HUD and radar map will not show up:

![Shot01244](https://github.com/EliotVU/UT2004-MutEmoticons/assets/5176385/1d0d8cd9-199a-460c-a800-4bfe991a5b55)
![Shot01245](https://github.com/EliotVU/UT2004-MutEmoticons/assets/5176385/311641d5-d44b-4435-af78-b99a96bcc092)
![Shot01246](https://github.com/EliotVU/UT2004-MutEmoticons/assets/5176385/f6b3409d-4ec7-4d53-aa19-e9e9530fe1d7)

**Comment by EliotVU** [comment]
This appears to be a bug with V1A only (it first checks for a xTeamGame before prioritizing specifically Onslaught, thus the Onslaught HUDClassType is displaced by the base HUD!)

This is not an issue in V1B, however the original release for V1B was lost, you'll have to re-compile the mod from the source code yourself.

**Comment by EliotVU** [comment]
Closing as redundant, fixed with V1B, see also https://github.com/EliotVU/UT2004-MutEmoticons/releases/tag/release-2.0

**Comment by Calypto** [comment]
Thanks. I tried the most recent release and it worked.
